name: Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:
concurrency:
  group: pages
  cancel-in-progress: true
jobs:
  ci:
    uses: cap-l-cc/my-home/.github/workflows/ci.yaml@main
  cd:
    runs-on: ubuntu-latest
    needs:
      - ci
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: assets
      - run: ls
