name: CI nd CD
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  branch-name:
    name: Get current branch name
    runs-on: ubuntu-latest
    outputs:
      branch-name: ${{ steps.branch-name.outputs.current_branch }}
    steps:
      - name: Get the current branch name
        id: branch-name
        uses: tj-actions/branch-names@v7
      - name: Print
        run: echo ${{ steps.branch-name.outputs.current_branch }}
  ci:
    name: Format and Prepare for deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
      - name: Get node version from Volta
        id: get-node-version
        uses: keita-hino/get-node-version-from-volta@main
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.get-node-version.outputs.nodeVersion }}
          cache: pnpm
      - name: Install dependencies
        run: pnpm i
        shell: bash
      - name: Generate CSS
        run: |
          pnpm css
          rm -rf src/css/main.css
      - name: Format
        run: pnpm fmt
      - name: Upload files
        uses: actions/upload-artifact@v3
        with:
          name: assets
          path: src
  cd:
    name: Deploy with Cloudflare Pages
    runs-on: ubuntu-latest
    needs:
      - ci
      - branch-name
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: assets
          path: assets
      - name: Deploy with Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: fff06038a70892193e0fa1e9e270436a
          projectName: my-home
          directory: assets
          branch: ${{ needs.branch-name.outputs.branch-name }}
          wranglerVersion: 3
